/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-green-600',
    'hover:bg-green-700',
    'bg-green-600',
    'hover:bg-gray-700',
    'bg-red-500',
    'hover:bg-red-700',
    'bg-green-600',
    'hover:bg-green-700',
    'bg-gray-400',
    'text-white',
    'font-bold',
    'py-2',
    'px-4',
    'rounded',
    'transition-colors',
    'cursor-not-allowed',
    'w-full',
    'border',
    'rounded-lg',
    'p-6',
    'bg-white',
    'shadow-sm',
    'bg-red-50',
    'border-red-200',
    'rounded-md',
    'p-4',
    'bg-green-50',
    'border-green-200',
    'bg-green-50',
    'border-green-200',
    'bg-yellow-50',
    'border-yellow-200',
    'p-3',
    'border-gray-300',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-green-500',
    'focus:border-transparent',
    'border-red-300',
    'focus:ring-red-500',
  ],
} 